### PR TITLE
FIX: memcached addServers() & getVersion() behavior

### LINKED ISSUE #7265: Memcached::getVersion PHP incompatibility
A PHP API inconsistency was discovered in HHVM 3.12.1 surrounding the `Memcached::getVersion` command.

### HHVM Version
HipHop VM 3.12.1 (rel)
Compiler: 1456975633_498207370
Repo schema: c0420568dcd107e78ab04e13142e17663b4804c2

### Standalone code, or other way to reproduce the problem
```
$servers = [
  ['host' => '127.0.0.1', 'port' => 11211, 'weight' => 50], // this server is functional
  ['host' => '127.0.0.1', 'port' => 11212, 'weight' => 50], // this server is *NOT* functional
];
$memcached = new \Memcached();
$memcached->addServers($servers);
var_dump($memcached->getVersion());
```
### Expected result
```
array(2) {
  '127.0.0.1:11211' =>
  string(6) "1.4.17"
  '127.0.0.1:11212' =>
  string(11) "255.255.255"
}
````
### Actual result
```
(bool) false
```

### PR DESCRIPTION
**Pull request by apeabody**
Numerous fixes for memcached behavior and tests
- Handle key based arrays for addServers() following PHP behavior.
- Return array for getVersion() following PHP behavior/docs.  This includes the server version of "255.255.255" for a failed connection.  
- New test case for key based servers array and getVersion() including failed connection.
- Numerous other memcached test fixes, especially inc_dec.php and dec_key.php.skipif

Behavior based on PHP 5.4.16 testing and PHP docs:
https://secure.php.net/manual/en/memcached.getversion.php
https://secure.php.net/manual/en/memcached.addservers.php

Closes #7265

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
This pull request has been imported into Phabricator, and discussion and review of the diff will take place at https://reviews.facebook.net/D61599

**Comment by Orvid** [comment]
@fredemmott The "Details" links for the failed tests don't currently point to anything useful. That's not intentional is it?

**Comment by fredemmott** [comment]
@Orvid : sorry, I've been using this as a test PR; the details links won't work until the 16th.

**Comment by apeabody** [comment]
@fredemmott, Looks like the test summary disappeared, any chance it will be coming back?  Especially as we're now past the 16th and I was hoping the details page would be working.

Thanks!

**Comment by fredemmott** [comment]
They disappeared as test results on github are tied to a specific hash, and the pull request was updated. They be back when I enable the automation (previously they were here because of me running the job by hand against just this PR), which should be within the next week or so.

**Comment by apeabody** [comment]
Got it, I haven't been able to replicate these failures locally (Trusty or CentOS-7), so I'll probably need to wait till then.  Thanks!

**Comment by fredemmott** [comment]
They're back early :) sorry, the automation won't share the test output (we can't realistically detect automatically if the failure is from an fb-specific extension). If the names of the specific tests (available at "Details") aren't sufficient, you need help from someone working on HHVM at Facebook.

**Comment by apeabody** [comment]
Great, thanks @fredemmott, hopefully @Orvid or someone can send/post in Phabricator some more details (just a sample would help).

**Comment by Orvid** [comment]
Well then, lets see what a raw copy/paste from our internal side looks like (after having checked for things that shouldn't be public)

Summary	Test	Details
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/get_version.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
003+   string(5) "0.0.0"
003-   string\(\d+\) "1\.\d+\.\d+"
005+   string(5) "0.0.0"
005-   string\(11\) "255\.255\.255"
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/decompression.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ Warning: failed to connect to localhost [111]: Connection refused in /data/sandcastle/boxes/instance-fbcode-fbsource-hphp-buck/fbcode/hphp/test/slow/ext_memcached/decompression.php on line 34
002+ Couldn't connect to memcache.
001- array(2) {
002- ...
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/get_set.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
001- array(1) {
002-   ["foo"]=>
003-   string(3) "bar"
004- }
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/memcached-getallkeys.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
001- NULL
002- array(4) {
003-   [0]=>
004-   string(5) "array"
005-   [1]=>
006-   string(6) "string"
007-   [2]=>
008-   string(3) "int"
009-   [3]=>
010-   string(6) "object"
011- }
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/types.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
003+ bool(false)
004+ bool(false)
005+ bool(false)
006+ bool(false)
007+ bool(false)
008+ bool(false)
009+ bool(false)
010+ bool(false)
011+ bool(false)
012+ bool(false)
013+ bool(false)
014+ bool(false)
015+...
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/key_with_space.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
003+ bool(false)
004+ bool(false)
001- bool(true)
002- string(5) "value"
003- bool(true)
004- string(5) "value"
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/callback.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
001- object(Memcached)#2 (0) {
002- }
003- string(13) "callback_test"
004- NULL
005- int(99)
006- int(99)
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/session_basic.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
002+ array(0) {
002- array\(1\) \{
003-   \["foo"\]\=\>
004-   int\(1\)
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/deletemulti.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
003+ bool(false)
004+ bool(false)
005+ bool(false)
006+ bool(false)
001- bool(true)
002- bool(true)
003- array(0) {
004- }
005- bool(true)
006- bool(true)
007- array(0) {
008- }
009- nothere NOT FOUND
010- n...
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/inc_dec.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
003+ bool(false)
004+ bool(false)
005+ bool(false)
006+ bool(false)
001- int\(0\)
002- int\(3\)
003- int\(2\)
005- array\(0\) \{
008+ NULL
006- \}
007- bool\(false\)
008- array\(0\) \{
009- \}
010- string\(2...
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/session_prefix.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
004+ 
005+ Warning: Failed calling MemcachedSessionModule::write() in /data/sandcastle/boxes/instance-fbcode-fbsource-hphp-buck/fbcode/hphp/test/slow/ext_memcached/session_prefix.php on line 18
006+ 
007+ Warning: Failed to write session data (memcached...
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/touch-binary-2.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ get status code mismatch, expected RES_NOTFOUND but got RES_SOME_ERRORS
002+ set status code mismatch, expected RES_SUCCESS but got RES_WRITE_FAILURE
003+ get status code mismatch, expected RES_SUCCESS but got RES_SOME_ERRORS
004+ 
005+ Fatal erro...
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/getmulti.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
003+ bool(false)
004+ Result not an array
002- bool(true)
003- bool(true)
004- bool(true)
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/delete.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
001- bool(true)
002- bool(true)
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/dec_key.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
002+ bool(false)
003+ bool(false)
004+ bool(false)
005+ bool(false)
006+ bool(false)
007+ bool(false)
008+ bool(false)
009+ bool(false)
010+ bool(false)
011+ bool(false)
012+ bool(false)
013+ bool(false)
014+ bool(false)
015+...
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/touch.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ Fatal error: c_Memcached_ni_touchbykey is not supported: Not Implemented in libmemcached versions below 1.0.2
001- bool(true)
002- bool(true)
003- OK
Detailed Result
✗failed	hphp/test:verify_slow_jit_repo - hphp/test/slow/ext_memcached/touch-binary.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ GET: SOME ERRORS WERE REPORTED
002+ 
003+ Fatal error: c_Memcached_ni_touchbykey is not supported: Not Implemented in libmemcached versions below 1.0.2
001- GET: SUCCESS
002- TOUCH: SUCCESS
003- TOUCH: SUCCESS
004- GET: SUCCESS
005- GET: SUCCES...
Detailed Result
✗failed	hphp/test:verify_slow_interp_repo - hphp/test/slow/ext_memcached/get_version.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
003+   string(5) "0.0.0"
003-   string\(\d+\) "1\.\d+\.\d+"
005+   string(5) "0.0.0"
005-   string\(11\) "255\.255\.255"
Detailed Result
✗failed	hphp/test:verify_slow_interp_repo - hphp/test/slow/ext_memcached/decompression.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ Warning: failed to connect to localhost [111]: Connection refused in /data/sandcastle/boxes/instance-fbcode-fbsource-hphp-buck/fbcode/hphp/test/slow/ext_memcached/decompression.php on line 34
002+ Couldn't connect to memcache.
001- array(2) {
002- ...
Detailed Result
✗failed	hphp/test:verify_slow_interp_repo - hphp/test/slow/ext_memcached/get_set.php (buildsystem: buck, compiler: gcc, sanitizer: none)	
001+ bool(false)
001- array(1) {
002-   ["foo"]=>
003-   string(3) "bar"
004- }
Detailed Result

**Comment by apeabody** [comment]
Great, this was very helpful.  This test appears to be using a MUCH older
version of libmemcached than I would have expected.  In particular
libmemcached appears to (undocumented) default the version values exactly
the opposite pre-0.46 (0 vs 255).  Took some serious digging to find it!

**Pull request closed without merging**
