### PR TITLE
Fix PHP_SELF -- as is it would create PHP_SELF as example.php/var/www/do...

### PR DESCRIPTION
**Pull request by joelastpass**
...croot which nothing expects for it to work that way.

### CODE REVIEW

**Comment by joelastpass** [comment]
This fixes a large number of PHP compatiability issues we ran into -- have been running this patch for months.

**Comment by jwatzman** [comment]
> This fixes a large number of PHP compatiability issues we ran into -- have been running this patch for months.

Nice, thanks for the PR! Happy to start taking a look at it when you submit the signed CLA (see above).

**Comment by joelastpass** [comment]
Success. You have digitally signed the Contributor License Agreement.
Signed: October 16, 2014  -- I've resent the copy we saved to
cla@facebook.com as well.

On Fri, Jan 23, 2015 at 1:41 PM, Josh Watzman <notifications@github.com>
wrote:

> This fixes a large number of PHP compatiability issues we ran into -- have
> been running this patch for months.
>
> Nice, thanks for the PR! Happy to start taking a look at it when you
> submit the signed CLA (see above).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/hhvm/pull/4699#issuecomment-71241910>.
>



-- 
*Joe Siegrist | CEO | LastPass.com <http://lastpass.com/> | **703.712.8315
x8304*

**Comment by fredemmott** [comment]
@joelastpass : was this a corporate CLA, or an individual one? If an individual one, what name was it submitted under? We've got nothing tied to your GitHub identity.

If you'd rather not say here, feel free to email me at fe@fb.com

**Comment by jwatzman** [comment]
Thanks! I've kicked off the test run for you. The rest of the review will take place on https://reviews.facebook.net/D32049 -- I'll add some comments there in a moment.

**Comment by fredemmott** [comment]
Will reopen once comments on reviews.facebook.net are responded to. https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Pull request closed without merging**
