### PR TITLE
Kill constants.h

### PR DESCRIPTION
**Pull request by simonwelsh**
It's empty and isn't included from anywhere, so nuke it.

Test Plan: collections test to make sure I didn't break the last IDL extensions

### CODE REVIEW

**Comment by simonwelsh** [comment]
I haven't removed it from `system/.gitignore` so that people don't accidentally commit it.

**Comment by sgolemon** [comment]
Too late @alexmalyshev already has this diff up.

**Comment by sgolemon** [comment]
Actually, your diff is way more complete.  Rebase once his lands though?

**Comment by simonwelsh** [comment]
Okay, will watch out for it.

**Comment by sgolemon** [comment]
c147397a876dc03d79eb1e4db9043e881d62b679

**Comment by sgolemon** [comment]
hrmmm I'm dumb and got confused.  This IS based on his diff.

**Comment by Orvid** [comment]
He killed it, this murders it.

**Pull request closed without merging**
