### PR TITLE
Do not use folly::Optional on iterator in store-elim.

### PR DESCRIPTION
**Pull request by wjywbs**
Clang 3.6 and 3.7 on mac crash with assertion "move constructor should not be
deleted".

https://github.com/llvm-mirror/clang/blob/e1d7b3bd4c2f9d0866ca7eaa4178a0c06815b607/include/clang/AST/DeclCXX.h#L919-L924

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
This pull request has been imported into Phabricator, and discussion and review of the diff will take place at https://reviews.facebook.net/D57855

**Comment by Orvid** [comment]
Perhaps it would be better to fix this in Folly rather than here?

**Comment by wjywbs** [comment]
This is very likely a clang bug because clang shouldn't crash.

**Comment by Orvid** [comment]
@wjywbs Ping on the review.

**Pull request closed without merging**
