### PR TITLE
fix soft link relative path require file problem

### PR DESCRIPTION
**Pull request by huzhiguang**
require soft link relative path's relative path,but get path is real path's relative path

### CODE REVIEW

**Comment by jwatzman** [comment]
Closing due to inactivity. https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Comment by huzhiguang** [comment]
Why not accept this patch?

**Comment by reeze** [comment]
@huzhiguang You may discuss it on Phabricator, there are some issues need to be resolved.

**Comment by jwatzman** [comment]
Yep, please see the above Phabricator link https://reviews.facebook.net/D31491 to see what the concerns raised. If you are going to continue iterating on this patch, feel free to reopen the PR.

**Pull request closed without merging**
