### PR TITLE
Fix cmp to test vasm simplication for PPC64

### PR DESCRIPTION
**Pull request by gut**
The improvement implemented on fa442471676c9550691c28fe31c9fee2edda0a05 is
arch-specific as a test may not be better than a cmp on every arch. So it
should actually be opt-in for other archs to make use of it.

Moreover PPC64 couldn't handle the test vasm after it's lower phase, therefore
a second call to lower was added to guarantee that the vasms emitted by
simplify and optimizeCopies are actually handled by PPC64 emitter. 

No significant overhead was noticed.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
This pull request has been imported into Phabricator, and discussion and review of the diff will take place at https://reviews.facebook.net/D62463

**Comment by ricklavoie** [comment]
Its not so much that test is faster than cmp, but that it encodes in less bytes, increasing code density.

**Comment by gut** [comment]
thanks for pointing it out. I didn't know the exact reason, just that X64's backend devs prefers it.

**Comment by gut** [comment]
Is this "fb/hphp-buck — Tests Failed" a concern?

**Comment by Orvid** [comment]
Nope, it's just a flaky internal test.

**Pull request closed without merging**
