### PR TITLE
add  "/usr/lib/x86_64-linux-gnu" paths to cmake/findGLib

### PR DESCRIPTION
**Pull request by shimondoodkin**
for docker, ubuntu image

### CODE REVIEW

**Comment by shimondoodkin** [comment]
signed cla

**Comment by apinski-cavium** [comment]
Most likely should add "/usr/lib/aarch64-linux-gnu" for the same reason.

**Comment by brunoalr** [comment]
@shimondoodkin Is it too late to include "/usr/lib/powerpc64le-linux-gnu/" as well?

**Comment by mofarrell** [comment]
@brunoalr I will add it.

**Comment by brunoalr** [comment]
@mofarrell thanks!

**Pull request closed without merging**
