### PR TITLE
revise callstubs defs for aarch64 target

### PR DESCRIPTION
**Pull request by swalk-cavium**
This commit https://github.com/facebook/hhvm/commit/98c4f446b683756cf7f98aef8fa9ac97d791b4c1
changed the registers presented to the allocator for the callstub Vinstr.  The comment says
it did not change the register sets for aarch64.  This is not correct.  This change caused an
internal assert to fire when it was trying to create spill space on the stack.  This sounds like
the problem seen on other hosts.

The standard regression tests were run with 6 option sets.  This brings the results back to
the normal baseline for the lab machine I use.

This fixes issue https://github.com/facebook/hhvm/issues/8396

### CODE REVIEW

**Comment by swalk-cavium** [comment]
@mxw , @ricklavoie - Can you review?

**Comment by ricklavoie** [comment]
This isn't the right fix. This change was made originally because the defs set was incorrect and a new register allocator we're working on exposed this bug. This pull request just undoes the fix for ARM, which means it will trigger that bug. The right fix is to do the same thing we did for x86 and remove registers (one is probably all thats required) from the kScratchCrossTraceRegs to reduce the register pressure.

**Comment by swalk-cavium** [comment]
Hi @ricklavoie,
I modeled the change after the x64 version and reduced the kScratchCrossTraceRegs
until the regression tests went back to baseline.

The regression tests were run with 6 option sets. The internal assert is gone.

**Comment by swalk-cavium** [comment]
Is there anything else I need to do for this one?

**Pull request closed without merging**
