### PR TITLE
Adding -std=c++11 for Intel compiler

### PR DESCRIPTION
**Pull request by domainname**

### CODE REVIEW

**Comment by jwatzman** [comment]
Please sign the CLA as above, we can't accept this until you do.

**Comment by domainname** [comment]
@jwatzman done.

**Comment by domainname** [comment]
@jwatzman what should I do now? Travis CI said the branch has failed checks.

**Comment by jwatzman** [comment]
Ignore travis. The Phabricator diff being landed indicates we'll pull it in. We're just having some test infra problems; I'll force-land it tomorrow.

**Comment by domainname** [comment]
Great!  Thanks for your time.

**Pull request closed without merging**
