### PR TITLE
close curl descriptor

### PR DESCRIPTION
**Pull request by wake-up-neo**
https://github.com/facebook/hhvm/issues/7076

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
This pull request has been imported into Phabricator, and discussion and review of the diff will take place at https://reviews.facebook.net/D60339

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by wake-up-neo** [comment]
all hacklang developers, who are using [\HH\Asio\curl_exec](https://docs.hhvm.com/hack/reference/function/HH.Asio.curl_exec/) function with **url as argument** or as **return await curl_exec($descriptor)**  will have an issue with deadlock of virtual machine after 100k+ function calls depending on your environment. hhvm will still alive as process but not responding. do not use this function in production before the pull request will be approved.

**Pull request closed without merging**
