### PR TITLE
Add scrypt extension to hhvm

### PR DESCRIPTION
**Pull request by joelastpass**
This is a HHVM extension wrapper of Colin Percival's scrypt. 
William Xu : williamxu15@gmail.com was the primary developer on this 
project here at LastPass.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
This pull request has been imported into Phabricator, and discussion and review of the diff will take place at https://reviews.facebook.net/D57267

**Comment by Orvid** [comment]
The mysql commit seems to have made it into this PR.

**Comment by Orvid** [comment]
ping?

**Comment by joelastpass** [comment]
Thanks, resubmitted without that commit.

**Comment by joelastpass** [comment]
Just noticed the phabricator comments as well, will address and resend.

**Comment by joelastpass** [comment]
I think this addresses all the phabricator comments, please take another look.

**Comment by joelastpass** [comment]
I believe all phabricator comments have been addressed, can you take another look?

**Comment by Orvid** [comment]
Yep, I was just looking at it yesterday. I'm trying to decide how to suggest handling the SSE vs. no SSE support (it's worth keeping the SSE), because all x64 targets that HHVM supports have at least SSE2. The problem comes from ARM and PPC, which (for the most part) don't have SSE (at the very least, the intrinsics are different). I'll make a couple of comments on phabricator.

**Comment by joelastpass** [comment]
Can we provide any assistance on getting this unstuck in your internal build process?  We're not sure how to help here.

**Comment by Orvid** [comment]
I was just looking at this, will give an update in a bit.

**Comment by Orvid** [comment]
It took me a bit to realize it, but we have an internal extension that was also named scrypt (it doesn't implement the same API that PHP exposes, and is dependent on some other internal stuff), so I have a diff up to rename the internal extension. Once that lands, this should build just fine.

**Comment by joelastpass** [comment]
Okay great.   Do the successful checks mean this is now ready to be merged?

**Pull request closed without merging**
