### PR TITLE
Use glob to find gdb scripts

### PR DESCRIPTION
**Pull request by reeze**
This could prevent the issue like #4792 happen again

### CODE REVIEW

**Comment by rrh** [comment]
lgtm

**Comment by reeze** [comment]
this seems didn't been imported to Phabricator   @JoelMarcey

**Comment by JoelMarcey** [comment]
Hi @reeze ... this came in on Friday PST, I believe. It should be imported by @fredemmott today.

**Comment by reeze** [comment]
@JoelMarcey  wasn't that imported automatically?

**Comment by JoelMarcey** [comment]
@reeze These is https://reviews.facebook.net/D33099, but @fredemmott needs to import the diff internally to start running tests, etc.

Though you are right, I am not sure why it wasn't stated here that it was imported to phabricator.

**Comment by reeze** [comment]
Get it,thanks.

**Pull request closed without merging**
