### PR TITLE
FastCGI socket owner, group and mode change support

### PR DESCRIPTION
**Pull request by kristapsk**
Adds three new hdf / ini settings: `Server.FileSocketOwner` / `hhvm.server.file_socket_owner`, `Server.FileSocketGroup` / `hhvm.server.file_socket_group`, `Server.FileSocketMode` / `hhvm.server.file_socket_mode` which allows to change owner, group and permissions for UNIX socket file used by FastCGI server. Should work similar as php-fpm `listen.owner`, `listen.group`, `listen.mode`. This allows running hhvm and front-end webserver (e.g. nginx) under different users through UNIX sockets.

Also added is support of specifying octal values for integer settings in php.ini.

P.S. php-fpm defaults to mode 0660, HHVM defaults to 0650. Shouldn't we also change that?

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@kristapsk Hi. Are you still planning on making any updates to this pull request, particularly around at least adding a test as requested? Thanks.

**Comment by kristapsk** [comment]
@JoelMarcey , yes. Just busy at daily job right now, can't get enough priority for this. Most likely will get to this at weekend.

What kind of other changes, besides adding tests, do you mean? As I understood from @sgolemon , it is ok to not split this PR into smaller ones, as it is small enough.

**Comment by JoelMarcey** [comment]
@kristapsk Thanks.

If @sgolemon is cool with your PR as-is, then that is fine with me. We both though would like tests added. :)

**Comment by JoelMarcey** [comment]
@kristapsk Did you make an update to your pull request? I see a couple of "update" notifications internally here, but I don't see any code changes.

**Comment by kristapsk** [comment]
No, not yet. Those "updates" are not from me.

**Comment by JoelMarcey** [comment]
Ok. Thanks!

**Comment by JoelMarcey** [comment]
@kristapsk Hi. Just as an FYI that due to our policy https://github.com/facebook/hhvm/wiki/Human-Timeouts, I am going to close this pull request tomorrow if we don't get an update before then. It is no problem to resubmit (and we encourage it), but we need to clear out our queue occasionally.

Thanks!

**Comment by kristapsk** [comment]
@JoelMarcey , finally looked closer at this. Isn't that these quick/slow tests run in command line mode? These changes are for FastCGI server, so testing should be done that way. I see there are server/fastcgi tests, but they are already failing for me...
```
$ hhvm/hhvm test/run test/server/fastcgi
Running 7 tests in 7 threads (0 in serial)

FAILED: test/server/fastcgi/server_root/subdoc/subdir/test.php
No test/server/fastcgi/server_root/subdoc/subdir/test.php.expect, test/server/fastcgi/server_root/subdoc/subdir/test.php.expectf, nor test/server/fastcgi/server_root/subdoc/subdir/test.php.expectregex. Is test/server/fastcgi/server_root/subdoc/subdir/test.php even a test?

FAILED: test/server/fastcgi/server_root/test_headers.php
No test/server/fastcgi/server_root/test_headers.php.expect, test/server/fastcgi/server_root/test_headers.php.expectf, nor test/server/fastcgi/server_root/test_headers.php.expectregex. Is test/server/fastcgi/server_root/test_headers.php even a test?

FAILED: test/server/fastcgi/Adoy/Client.php
No test/server/fastcgi/Adoy/Client.php.expect, test/server/fastcgi/Adoy/Client.php.expectf, nor test/server/fastcgi/Adoy/Client.php.expectregex. Is test/server/fastcgi/Adoy/Client.php even a test?

FAILED: test/server/fastcgi/server_root/test_get.php
No test/server/fastcgi/server_root/test_get.php.expect, test/server/fastcgi/server_root/test_get.php.expectf, nor test/server/fastcgi/server_root/test_get.php.expectregex. Is test/server/fastcgi/server_root/test_get.php even a test?

FAILED: test/server/fastcgi/server_root/hello.php
No test/server/fastcgi/server_root/hello.php.expect, test/server/fastcgi/server_root/hello.php.expectf, nor test/server/fastcgi/server_root/hello.php.expectregex. Is test/server/fastcgi/server_root/hello.php even a test?

5 tests failed
(╯°□°）╯︵ ┻━┻

See the diffs:
cat test/server/fastcgi/Adoy/Client.php.diff
cat test/server/fastcgi/server_root/hello.php.diff
cat test/server/fastcgi/server_root/subdoc/subdir/test.php.diff
cat test/server/fastcgi/server_root/test_get.php.diff
cat test/server/fastcgi/server_root/test_headers.php.diff

For xargs, list of failures is available using:
cat /tmp/test-failurestjQb26

For xargs, list of passed tests is available using:
cat /tmp/tests-passedLMM50e

Run these by hand:
./hhvm/hhvm -c test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/neonz/git/hhvm/verify.hhbc -vEval.Jit=true    -vResourceLimit.CoreFileSize=0    --file 'test/server/fastcgi/Adoy/Client.php'
./hhvm/hhvm -c test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/neonz/git/hhvm/verify.hhbc -vEval.Jit=true    -vResourceLimit.CoreFileSize=0    --file 'test/server/fastcgi/server_root/hello.php'
./hhvm/hhvm -c test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/neonz/git/hhvm/verify.hhbc -vEval.Jit=true    -vResourceLimit.CoreFileSize=0    --file 'test/server/fastcgi/server_root/subdoc/subdir/test.php'
./hhvm/hhvm -c test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/neonz/git/hhvm/verify.hhbc -vEval.Jit=true    -vResourceLimit.CoreFileSize=0    --file 'test/server/fastcgi/server_root/test_get.php'
./hhvm/hhvm -c test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/neonz/git/hhvm/verify.hhbc -vEval.Jit=true    -vResourceLimit.CoreFileSize=0    --file 'test/server/fastcgi/server_root/test_headers.php'

Re-run just the failing tests:
test/run --threads 5 'test/server/fastcgi/Adoy/Client.php' 'test/server/fastcgi/server_root/hello.php' 'test/server/fastcgi/server_root/subdoc/subdir/test.php' 'test/server/fastcgi/server_root/test_get.php' 'test/server/fastcgi/server_root/test_headers.php'
```

**Comment by JoelMarcey** [comment]
@kristapsk Hi. You need to run the fastcgi tests like this:

 `hhvm/hhvm test/run fastcgi`

or

`hhvm/hhvm test/run test/server/fastcgi/tests`

There are only 2 fastcgi tests to be run there.

**Comment by jwatzman** [comment]
Still waiting on tests; closing due to inactivity per https://github.com/facebook/hhvm/wiki/Human-Timeouts. If you'd like to come back to this, feel free to reopen this PR (we can easily revive things), but closing out for now.

**Comment by helgi** [comment]
@kristapsk did you get any further with the testing? Exactly the functionality I need

**Comment by kristapsk** [comment]
@helgi , no, sorry, currently busy with other things. And can't promise anything right now.

**Comment by kristapsk** [comment]
I will not work on this anymore, as I implemented workaround for the problem I was trying to solve.

My problem was that nginx and hhvm runs under different UNIX users, so by default nginx don't have write permission on hhvm socket. But yesterday I implemented umask change for hhvm processes (https://github.com/skyfms/portage-overlay/commit/44087e342b9f23397b1c84a5c55d7747e3c183b0) which allows to make all files created by hhvm group writeable by default (0002). So now I just needed to add nginx user to hhvm group, and this solution is perfectly fine for us.

**Pull request closed without merging**
