### PR TITLE
optional integer overflow logging/exception

### PR DESCRIPTION
**Pull request by zuercher**
Adds a configuration setting hhvm.hack.lang.check_int_overflow. When enabled,
compilation generates overflow variants of the Add, MinusEqual, Mul, MulEqual,
PlusEqual, PostDec, PostInc, PreDec, PreInc, and Sub instructions (with O
suffixes). During execution, if an integer overflow occurs, the variant
instructions raise an E_WARNING (if check_int_overflow=1) or throws an
ArithmeticError (if check_int_overflow=2).

### CODE REVIEW

**Comment by fredemmott** [comment]
Thank you so much! This looks great to me - importing and getting better reviewers :)

**Comment by fredemmott** [comment]
Several tests e.g. hphp/test/slow/int_overflow/inc_dec_1.php (and several others in that directory) are failing in repo-authoritative mode

**Comment by zuercher** [comment]
Hm. Ok. I'll take a look.

**Comment by zuercher** [comment]
Ah, I see. The Hack.Lang.CheckIntOverflow flag needs to be set at compile time and I failed to add it to the .hphp_opts files. I re-ran these tests locally with `test/run -m interp -r` and `test/run -r` flags in addition to the default.

**Comment by zuercher** [comment]
@fredemmott any word on this?

**Comment by fredemmott** [comment]
sorry, think I missed the last update given the timing :/

**Comment by fredemmott** [comment]
Main test runs are clean, a few of the unusual ones are taking longer than expected.

**Comment by fredemmott** [comment]
reran tests, looks bogus. Poking people for review.

**Comment by fredemmott** [comment]
Approved internally, waiting for clean test run.

If run is clean, we'll be landing this with https://gist.github.com/fredemmott/7ecacbd1ba3ef220a6664d9443d5b976

If we find issues, we'd appreciate it if you could merge in those - but don't update this PR just for those (updating the PR resets a bunch of review/test state)

**Comment by fredemmott** [comment]
One that we need timed out :( rebasing and re-running

**Comment by fredemmott** [comment]
Had the specific one I needed clean, but have other failures; confident they're unrelated so landing, but chance of a revert if I'm wrong.

**Pull request closed without merging**
