### PR TITLE
Proposed fix for issue #6168 eliminates segfault and correctly passes error back

### PR DESCRIPTION
**Pull request by apeabody**

### CODE REVIEW

**Comment by apeabody** [comment]
New behavior:

hhvm --php -r '(new DOMDocument)->save("");'

Warning: filename is missing in /tmp/php-wrap-9jof2y on line 2

**Comment by SiebelsTim** [comment]
This needs a test in `slow/ext_dom`. In particular, you'll see that you didn't match php error message, which is `DOMDocument::save(): Invalid Filename`.

**Comment by apeabody** [comment]
Ahh, understood.  I now assume this is the desired behavior:

hhvm --php -r '(new DOMDocument)->save("");'

Warning: DOMDocument::save(): Invalid Filename in /tmp/php-wrap-1e4KI7 on line 2

I'll develop a test and check it in tonight.

**Comment by SiebelsTim** [comment]
exactly :)

**Comment by dpaneda** [comment]
I don't think this is the proper way to fix this issue. The problem occurs when a warning is generated when opening the file, not only when the filename is empty.

For example if you try to save to a directory:
```
<?php
$doc = new DOMDocument();
$doc->save('/tmp');
```

This is a gdb stacktrace of the problem (sorry about the missing symbols).
```
#0  0x00000000010a70b3 in HPHP::jit::FixupMap::fixupWork(HPHP::ExecutionContext*, HPHP::ActRec*) const ()
#1  0x0000000002519f8b in HPHP::jit::MCGenerator::syncWork() ()
#2  0x0000000000abe0c2 in HPHP::ExecutionContext::handleError(std::string const&, int, bool, HPHP::ExecutionContext::ErrorThrowMode, std::string const&, bool) ()
#3  0x0000000002561d39 in HPHP::raise_warning(char const*, ...) ()
#4  0x0000000000acefed in HPHP::FileStreamWrapper::open(HPHP::String const&, HPHP::String const&, int, HPHP::req::ptr<HPHP::StreamContext> const&) ()
#5  0x0000000000ad442e in HPHP::File::Open(HPHP::String const&, HPHP::String const&, int, HPHP::req::ptr<HPHP::StreamContext> const&) ()
#6  0x000000000178b9ac in ?? ()
#7  0x000000000178ef0e in ?? ()
#8  0x00007ffff11d2a87 in xmlSaveFormatFileEnc () from /usr/lib/libxml2.so.2
#9  0x00000000015c6254 in HPHP::c_DOMDocument_ni_save(HPHP::ObjectData*, HPHP::String const&, long) ()
#10 0x0000000007200221 in ?? ()
#11 0x00000000025104f9 in enterTCHelper ()
#12 0x0000000000fb8066 in ?? ()
#13 0x0000000001236d7b in HPHP::jit::MCGenerator::enterTC(unsigned char*, HPHP::ActRec*) ()
#14 0x000000000250f8b7 in HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) ()
#15 0x00000000025551df in HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) ()
#16 0x000000000255505f in ?? ()
#17 0x0000000000a4ed79 in HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) ()
#18 0x0000000000b443db in HPHP::hphp_invoke(HPHP::ExecutionContext*, std::string const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::string const&, std::string const&, bool&, std::string&, bool, bool, bool) ()
#19 0x0000000000b44a35 in HPHP::hphp_invoke_simple(std::string const&, bool) ()
#20 0x0000000000b5b1b7 in ?? ()
#21 0x0000000000b5be5f in HPHP::execute_program(int, char**) ()
#22 0x00000000009b39e4 in main ()
```

**Comment by paulbiss** [comment]
@dpaneda is right. `xmlSaveFormatFileEnc` calls into a library that loses the frame-pointers that we need later to reconstruct the VM frames before raising warnings/errors. The fix here is simple you need a `VMRegAnchor _;` at the top of the function to eagerly sync the VM context.

**Comment by apeabody** [comment]
Thanks for the advice everyone.  Adding VMRegAnchor _; does fix the segfault issues, etc.  However the errors passed back don't match the PHP ones such as DOMDocument::save(): Invalid Filename.  Is that still the desired functionality?

./hhvm --php -r '(new DOMDocument)->save("");'

Warning: Is a directory in /tmp/php-wrap-GI6GlT on line 2

**Comment by apeabody** [comment]
Complete.  Added relevant test: slow/ext_domdocument/domdocument_save_invalid_filename.php

**Comment by JoelMarcey** [comment]
@apeabody I think for now the error not matching PHP is ok. The fixing of the segfault is more important.

**Pull request closed without merging**
