### PR TITLE
adding fix for proper case insensitive comparisons of single byte, no…

### PR DESCRIPTION
**Pull request by drewklein**
…n latin characters

This fixes Issue #7157

### CODE REVIEW

**Comment by Orvid** [comment]
@sdwilsh Any idea why the bot hasn't commented with the CLA message?

**Comment by sdwilsh** [comment]
The timing of this pull request lines up pretty well when the workflow managed to break for the facebook org doing something with a pull request.  I'm going to dig in more, but that might have something to do with it.

**Comment by sdwilsh** [comment]
So it looks like the code to auto-import to phabricator runs before the CLA bot has a chance to comment.  To top it off, it can't import until we have a signed CLA.

For now, let's get it moving along manually while I figure out a fix.

**Comment by sdwilsh** [comment]
@facebook-github-bot cla

**Comment by sdwilsh** [comment]
https://code.facebook.com/cla is the URL to go to.  Importing won't happen until that is done.

D3440532 in Facebook's internal phabricator will fix this moving forward.

**Comment by drewklein** [comment]
I believe I should already be on Intel's CLA.  Greg Bentley put in a
request to add me a few weeks ago.

**Comment by Orvid** [comment]
@sdwilsh Which side needs to deal with this? We already have an organization CLA for Intel.

**Comment by drewklein** [comment]
@gdbentley Has asked multiple times to get me added to the Intel CLA and we've been assured it would happen.

**Comment by sdwilsh** [comment]
@caabernathy is dealing with this.

**Comment by facebook-github-bot-4** [comment]
This pull request has been imported into Phabricator, and discussion and review of the diff will take place at https://reviews.facebook.net/D59709

**Pull request closed without merging**
