### PR TITLE
Potential aarch64 changes

### PR DESCRIPTION
**Pull request by ajasty-cavium**
Request creation of aarch64 tracking branch. Current test status is 157 failures on quick test. Would like to coordinate changes with HHVM team as possible.

### CODE REVIEW

**Comment by ajasty-cavium** [comment]
Additional changes bring quick test-failures to 5 in release builds. Please review and comment on suitability.

**Comment by ajasty-cavium** [comment]
Additional changes bring quick test-failures to 5 in release builds. Please review and comment on suitability.

**Comment by edwinsmith** [comment]
Hi - we're commenting on phabricator -- Just wanted to make sure you saw the comments, in case you're new to using Phabricator.

**Comment by edwinsmith** [comment]
Hi, to comment on the phabricator diffs, please just register your github username at reviews.facebook.net.  then we can use phabricator for review feedback (our preferred workflow).

**Comment by edwinsmith** [comment]
I think this change is obsoleted by https://github.com/facebook/hhvm/pull/5183, if that sounds right, can you confirm?  Or trim it back to just the things that aren't in 5183?

**Comment by apinski-cavium** [comment]
Yes this is obsoleted by #5183.  That is I started with the changes from here and went forward from there and placed it all into #5183.

**Comment by edwinsmith** [comment]
closing in favor of #5183

**Comment by edwinsmith** [comment]
(second try) closing in favor of #5183

**Pull request closed without merging**
