### PR TITLE
Rationalize hphpize/dynamic extension loading

### PR DESCRIPTION
**Pull request by lavagetto**
Remove HHVM_API_VERSION (unused and deprecated) in favour of the universally used HHVM_VERSION_BRANCH in hphpize

### CODE REVIEW

**Comment by Orvid** [comment]
Ping on the changes required for this.

**Comment by lavagetto** [comment]
@Orvid sorry, I had my plate full for a few weeks, I'll take a stab at it today.

**Comment by Orvid** [comment]
ping

**Comment by lavagetto** [comment]
@Orvid I reduced this PR to the first patch only, I'll submit the second one as a separate PR as you requested

**Pull request closed without merging**
