### PR TITLE
Remove warning on srand and mt_srand functions if first parameter is not a long

### PR DESCRIPTION
**Pull request by noony**

### CODE REVIEW

**Comment by fredemmott** [comment]
Why? This introduces a silent failure.

**Comment by noony** [comment]
To fit with php behavior.

**Comment by SiebelsTim** [comment]
for which version?
https://3v4l.org/njrWv

**Comment by SiebelsTim** [comment]
The warning itself is valid for most cases. 
The only case where we warn and php doesn't is when passing `true` or `false`.

**Comment by fredemmott** [comment]
Not taking this: inaccurate, and for true/false, the incompatibility seems worth the warning.

**Pull request closed without merging**
