### PR TITLE
dns_get_record must return by default an empty array not null

### PR DESCRIPTION
**Pull request by noony**

### CODE REVIEW

**Comment by sgolemon** [comment]
Sorry, I had to revert this due to a test failure that snuck through CI.
Should be able to re-land it soon though.

**Comment by noony** [comment]
Ok no problem @sgolemon something doesn't have same comportement than php in my pr ?

**Comment by sgolemon** [comment]
FB-internal code that makes bad assumptions about the return value of dns_get_record().  It's our bug and I'mma fix it.  I just don't want a bunch of web-devs getting sort at me while it's broken. :D

**Comment by JoelMarcey** [comment]
I am going to close this since we have the needed internal fix in and I have a diff up to unrevert the revert.

D2938499

**Pull request closed without merging**
