### PR TITLE
refactor FastLZ cmake finder

### PR DESCRIPTION
**Pull request by jrobeson**
Changes of note:

 * actually find the library in cmake (instead of specifying manually)
 * rename from libfastlz to fastlz to match the library name
 * don't add the third-party includes if we already specified the includes dir

### CODE REVIEW

**Comment by glensc** [comment]
please consider adding to 3.3-LTS branch as well. thanks!

**Comment by paulbiss** [comment]
cc @jwatzman

**Comment by paulbiss** [comment]
Also, in general if you want something backported you should open a PR with the cherry-pick against that branch so we can discuss it there.

**Comment by glensc** [comment]
I will make PR. thanks

**Pull request closed without merging**
