### PR TITLE
fix CLI client exit hang

### PR DESCRIPTION
**Pull request by zuercher**
Summary:
Per #8430, CLI client does not exit upon script termination because the
client's closure of the server's stderr does not trigger a read event
in all cases, leaving the client waiting to join a thread that will never
terminate. Modifies the stderr reader to use folly::AsyncPipeReader to
avoid the hang.

fixes facebook/hhvm#8430

### CODE REVIEW

**Comment by fredemmott** [comment]
Waiting for full review; in the mean time:
- lint: tabs vs spaces. Spaces please :)
- lint: Screen Shot 2019-06-27 at 12 05 14 PM
- I'm seeing errors like:

```
error: no matching function for call to ‘folly::AsyncPipeReader::AsyncPipeReader(folly::EventBase*, folly::NetworkSocket)’
     return UniquePtr(new AsyncPipeReader(std::forward<Args>(args)...));
```

This could be that you need https://github.com/facebook/hhvm/commit/53de4b54671286ea374028170f866f24846ed2db to be un-reverted (I'm working on that at the moment), or just that particularly old GCCs (I think the oldest we use is 5.3) need some casts

**Comment by zuercher** [comment]
@fredemmott re: the error -- I originally just used the bare fd, but synced master just before I published the PR and it seems that the fd for the AsyncPipeReader had been replaced with folly::NetworkSocket. Should I should merge master again and switch back to fds?

**Comment by fredemmott** [comment]
> @fredemmott re: the error -- I originally just used the bare fd, but synced master just before I published the PR and it seems that the fd for the AsyncPipeReader had been replaced with folly::NetworkSocket. Should I should merge master again and switch back to fds?

Heh, now getting this on a different build config:

```
hphp/runtime/vm/extern-compiler.cpp:210:71: error: no matching function for call to ‘folly::AsyncPipeReader::newReader(std::unique_ptr<folly::EventBase>::pointer, int&)’
[CONTEXT]      m_reader = folly::AsyncPipeReader::newReader(m_eventBase.get(), fd);
[CONTEXT]                                                                        ^
hphp/runtime/vm/extern-compiler.cpp:210:71: error: no matching function for call to ‘folly::AsyncPipeReader::newReader(std::unique_ptr<folly::EventBase>::pointer, int&)’
[CONTEXT]      m_reader = folly::AsyncPipeReader::newReader(m_eventBase.get(), fd);
[CONTEXT]                                                                        ^
```

I think we need both approaches - gated by `#ifdef FACEBOOK` - until 53de4b5 is in and stays in :(

**Comment by fredemmott** [comment]
We're seeing intermittent failures along these lines:

```
Using host libthread_db library "/usr/local/fbcode/platform007/lib/libthread_db.so.1".
__libc_read (nbytes=8192, buf=0x7efe78ad5000, fd=15) at ../sysdeps/unix/sysv/linux/read.c:26

Thread 5 (Thread 0x7efe719de700 (LWP 589064)):
#0  do_sigwait (sig=0x7efe719d6724, set=<optimized out>) at ../sysdeps/unix/sysv/linux/sigwait.c:61
#1  __sigwait (sig=0x7efe719d6724, set=<optimized out>) at ../sysdeps/unix/sysv/linux/sigwait.c:96
#2  __sigwait (set=<optimized out>, sig=0x7efe719d6724) at ../sysdeps/unix/sysv/linux/sigwait.c:89
#3  0x000000000cf5a989 in HPHP::(anonymous namespace)::handle_signals(void*) ()
#4  0x00007efea4f686b6 in start_thread (arg=0x7efe719de700) at pthread_create.c:465
#5  0x00007efea441febf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7efe7c4cf700 (LWP 588978)):
#0  0x00007efea4413ebe in __GI___poll (fds=0x7efe7c4c7748, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x000000000818e016 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<HPHP::(anonymous namespace)::ExternCompiler::start()::{lambda()#1}> > >::_M_run() ()
#2  0x00007efea5a70680 in std::execute_native_thread_routine (__p=0x7efe9d3281b0) at ../../../.././libstdc++-v3/src/c++11/thread.cc:83
#3  0x00007efea4f686b6 in start_thread (arg=0x7efe7c4cf700) at pthread_create.c:465
#4  0x00007efea441febf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7efe9f1ff700 (LWP 588579)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7efea040a810) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7efea040a858, cond=0x7efea040a7e8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7efea040a7e8, mutex=0x7efea040a858) at pthread_cond_wait.c:655
#3  0x000000000e2e3081 in background_thread_entry ()
#4  0x00007efea4f686b6 in start_thread (arg=0x7efe9f1ff700) at pthread_create.c:465
#5  0x00007efea441febf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7efe9fdff700 (LWP 588578)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7efea040a674) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7efea040a6b8, cond=0x7efea040a648) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7efea040a648, mutex=0x7efea040a6b8) at pthread_cond_wait.c:655
#3  0x000000000e2e38d1 in background_thread_entry ()
#4  0x00007efea4f686b6 in start_thread (arg=0x7efe9fdff700) at pthread_create.c:465
#5  0x00007efea441febf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7efea92f9e40 (LWP 588566)):
#0  __libc_read (nbytes=8192, buf=0x7efe78ad5000, fd=15) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=15, buf=0x7efe78ad5000, nbytes=8192) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x000000000931e0a8 in HPHP::PlainFile::readImpl(char*, long) ()
#3  0x00000000092835c8 in HPHP::File::read() ()
#4  0x0000000009321331 in HPHP::PlainFile::read() ()
#5  0x000000000808a31e in HPHP::f_stream_get_contents(HPHP::Resource const&, int, int) ()
#6  0x000000001421beaf in ?? ()
#7  0x000000001060006f in ?? ()
#8  0x00007efe00000054 in ?? ()
#9  0x00007ffe3c3b86a0 in ?? ()
#10 0x0000000008968994 in HPHP::jit::enterTCImpl(unsigned char*, HPHP::ActRec*) ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
[Inferior 1 (process 588566) detached]



[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/local/fbcode/platform007/lib/libthread_db.so.1".
0x00007efea4413ebe in __GI___poll (fds=0x7ffe3c3b8798, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29

Thread 1 (Thread 0x7efea92f9e40 (LWP 588590)):
#0  0x00007efea4413ebe in __GI___poll (fds=0x7ffe3c3b8798, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x000000000cdea03e in HPHP::LightProcess::runShadow(int) ()
#2  0x000000000cdeb57a in HPHP::LightProcess::createDelegate() ()
#3  0x0000000008191655 in HPHP::(anonymous namespace)::CompilerManager::ensure_started() [clone .constprop.833] ()
#4  0x0000000008192159 in HPHP::compilers_start() ()
#5  0x000000000934dfa3 in HPHP::hphp_process_init() ()
#6  0x000000000935cd04 in HPHP::execute_program_impl(int, char**) ()
#7  0x000000000935fc21 in HPHP::execute_program(int, char**) ()
#8  0x0000000003b59b85 in main ()
[Inferior 1 (process 588590) detached]



[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/local/fbcode/platform007/lib/libthread_db.so.1".
0x00007fcd7e8f1641 in __libc_read (fd=fd@entry=0, buf=buf@entry=0x1f231d0, nbytes=nbytes@entry=65536) at ../sysdeps/unix/sysv/linux/read.c:26

Thread 1 (Thread 0x7fcd7f228c80 (LWP 588977)):
#0  0x00007fcd7e8f1641 in __libc_read (fd=fd@entry=0, buf=buf@entry=0x1f231d0, nbytes=nbytes@entry=65536) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x00000000013278a5 in caml_read_fd (fd=0, flags=<optimized out>, buf=buf@entry=0x1f231d0, n=65536) at unix.c:77
#2  0x000000000131ed82 in caml_input_scan_line (channel=channel@entry=0x1f23180) at io.c:373
#3  0x000000000131fc3e in caml_ml_input_scan_line (vchannel=<optimized out>) at io.c:815
#4  0x0000000000bab263 in camlPervasives__scan_1283 () at pervasives.ml:433
#5  0x00000000004172d0 in camlHh_single_compile__read_message_13072 () at /data/sandcastle/boxes/trunk-hg-fbcode-fbsource/fbcode/hphp/hack/src/hh_single_compile.ml:232
#6  0x0000000000417104 in camlHh_single_compile__dispatch_loop_13070 () at /data/sandcastle/boxes/trunk-hg-fbcode-fbsource/fbcode/hphp/hack/src/hh_single_compile.ml:245
#7  0x000000000041c97e in camlHh_single_compile__entry () at /data/sandcastle/boxes/trunk-hg-fbcode-fbsource/fbcode/hphp/hack/src/hh_single_compile.ml:716
#8  0x000000000040a7e9 in caml_program ()
#9  0x000000000132ce8a in caml_start_program ()
#10 0x000000000132d1c5 in caml_startup_exn (argv=0x7ffff5610228) at startup.c:144
#11 0x000000000132d1f9 in caml_startup (argv=<optimized out>) at startup.c:149
#12 0x000000000132d222 in caml_main (argv=<optimized out>) at startup.c:158
#13 0x0000000000407dec in main (argc=<optimized out>, argv=<optimized out>) at main.c:37
[Inferior 1 (process 588977) detached]



0x00007f0b2772da3c in waitpid () from /lib64/libc.so.6

Thread 1 (process 589222):
#0  0x00007f0b2772da3c in waitpid () from /lib64/libc.so.6
#1  0x000055fe031fda44 in waitchld.isra ()
#2  0x000055fe031ff07b in wait_for ()
#3  0x000055fe031ee8a4 in execute_command_internal ()
#4  0x000055fe03234946 in parse_and_execute ()
#5  0x000055fe031d7800 in run_one_command ()
#6  0x000055fe031d6419 in main ()
[Inferior 1 (process 589222) detached]
```

No particular test - but if you run /all/ of them (quick, slow, zend), generally something will fail.

Additionally, `hphp/test/slow/dv_array/ext_factparse.php` is made flakey by this test; we're seeing errors like:

```
662+ E0708 10:46:27.000000 1080273 folly/io/async/EventHandler.cpp:93] EventBase: failed to register event handler for fd 132: No such file or directory
663+ E0708 10:46:27.000000 1080313 folly/io/async/EventHandler.cpp:93] EventBase: failed to register event handler for fd 369: No such file or directory
```

**Comment by zuercher** [comment]
Seems like this doesn't work correctly either. I thought of a different approach, that's also a smaller change. If I can get it working do you prefer that I update this PR or abandon it and start a fresh one?

**Comment by fredemmott** [comment]
If it's a tweak to this, update this one - but if it'svery different, probably best to abandon this one and get a clean history.

**Comment by zuercher** [comment]
Closing in favor of #8531.

**Pull request closed without merging**
