### PR TITLE
Aarch64 - Add a few more folder methods

### PR DESCRIPTION
**Pull request by swalk-cavium**
There were a few opportunities for additional folder methods in Aarch64.

I ran the regression suite with six option sets.  No new regressions detected.

echo "Test Started - `date`"

HPHP_TEST=all
PATH=`pwd`/hphp/hhvm:${PATH}
 
echo "/usr/bin/php hphp/test/run -v -m interp ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m interp ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m interp -r ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m interp -r ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=0' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=0' ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0' ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=1' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=1' ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1' ${HPHP_TEST} || true

echo "Test Ended - `date`"

### CODE REVIEW

**Comment by swalk-cavium** [comment]
@mxw - New Pull Request

**Comment by mxw** [comment]
Do you have any examples of TRACE output that shows this doing something?

**Comment by swalk-cavium** [comment]
Unfortunately, no.  That's why I took the extra time to run various option sets.
The code is very close to the x64 version.  The copy folder is byte-for-byte identical.

The last time I asked on the IRC about injecting specific code I didn't get a really good
answer.

Do you have any suggestions for further testing?

**Comment by mxw** [comment]
Hrm... this seems like the kind of thing that would be done in the simplifier, but I guess we're already doing it here for x64.  Okay, works for me.

**Pull request closed without merging**
