### PR TITLE
arm: Stop emitting moves for `copy rN rN`

### PR DESCRIPTION
**Pull request by cmuellner**
This adds a simple optimization, which is already in place for x86.

Signed-off-by: Christoph Muellner <christoph.muellner@theobroma-systems.com>

### CODE REVIEW

**Comment by cmuellner** [comment]
@mxw : please review
@dave-estes @jim-saxman @swalk-cavium : please test if possible
Notification also for @ptomsich

**Comment by mxw** [comment]
I'm surprised to see that line in `vasm-x64.cpp`...

Did you confirm whether this diff actually has any effect in practice—and if so, can you post an example where you get different code?  I'm pretty sure that the register allocator will resolve any self-copies away.

**Comment by cmuellner** [comment]
@mxw - I think you are right. vasm-xls.cpp:2177 should do that already. However even `void Vgen::emit(const copy2& i)` in vasm-x64.cpp has similar code (`if (s0 != d0)...`). I've just started a test run with an assertion for `i.s != i.d`. Let's if the `all` test set triggers it. If not, should I prepare a patch for x86?

**Comment by mxw** [comment]
It's possible that this code predates that behavior in vasm-xls.

In any case, it's probably better to have this check in the emitter than not.  Having it makes the emitter more independent of the register allocator's particular policy around copy elision.  I was just curious if you actually saw this diff having any effect—that would probably indicate a bug in our XLS implementation.

Let me know what you find, but we can just land this as-is.

**Comment by cmuellner** [comment]
The assertion did not trigger. I.e. the register allocator does its job well.

While the tests were running I had a look at the emit function for copy2 and adapted this to a form, which matches the x86 code (i.e. add the self-assignment protection and remove the use of reg-algorithms). Re-testing with this change as well showed again no regressions on aarch64.

**Comment by jim-saxman** [comment]
Works for me.

**Pull request closed without merging**
