### PR TITLE
Update Kohana framework to v3.3.4

### PR DESCRIPTION
**Pull request by enov**
Update the tested Kohana framework to v3.3.4

Thanks.

### CODE REVIEW

**Comment by fredemmott** [comment]
Reverting this, appears untested, and breaks the  test runner: 'ERROR: Could not get tests for kohana'

**Comment by enov** [comment]
> breaks the test runner: 'ERROR: Could not get tests for kohana'

Sorry to hear this. Just applied the same changes to `frameworks.yaml` on a newly cloned repo, and:

```
~/hhvm/hphp/test/frameworks$ hhvm run.php --record kohana
```

```
Found 369 tests for kohana. Each test could have more than one data set, making the total number be actually higher.
Resetting the expect file for kohana. Establishing new baseline with gray dots...
Establishing baseline statuses for kohana with gray dots...
Beginning the unit tests.....
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................All tests ran as expected.


          _
         /(|
        (  :
       __\  \  _____
     (____)  -|
    (____)|   |
     (____).__|
      (___)__.|_____

ALL TESTS COMPLETE!
SUMMARY:
kohana=99.86

To run differing tests (if they exist), see above for the
commands or the results/.diff file. To run erroring or
fataling tests see results/.errors and results/.fatals
files, respectively
```

So basically, same Kohana version v3.3.4, same commit hash 363c59ee298e1f5abe797e5efdf1c44431800a78, and the test runner did not complain, but it well generated the same `results/kohana.expect`.

Note: have a symlinked `usr/bin/hhvm` in `~/hhvm/hphp/hhvm/hhvm` (this vps has not enough RAM to compile from scratch)

```
hhvm --version
```

```
HipHop VM 3.7.2 (rel)
Compiler: tags/HHVM-3.7.2-0-gfc9f29b2799933d8215faaadfa83de722df64e26
Repo schema: 34f16546e395aed44ad434467b6f96c89b0d8a8b
```


Thanks.

**Comment by fredemmott** [comment]
Fails on master, but it's not actually a problem with kohana - the autotypecheck stuff is having trouble with all the frameworks :( will unrevert and dsiable the autotypecheck

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/commit/4f81d18f110faeb890d32bb16c62158ca99d2ae7

**Pull request closed without merging**
