### PR TITLE
Correction for load/store exclusive disassembly

### PR DESCRIPTION
**Pull request by swalk-cavium**
This brings forward some of the changes in vixl which has to do with
the disassembly of the loadStoreExclusive Aarch64 instructions.  It was
noticed that some instructions where not disassembled correctly when
examining the output from TRACE=printir:9

Before
====
    478     (03) IncProfCounter<1>
    479         Main:
    480               0x11a00030  d2800100              movz x0, #0x8
    481               0x11a00034  f2b4f000              movk x0, #0xa780, lsl #16
    482               0x11a00038  f2dfffe0              movk x0, #0xffff, lsl #32
    483               0x11a0003c  c85f7c12              unimplemented (Unimplemented)
    484               0x11a00040  f1000652              subs x18, x18, #0x1 (1)
    485               0x11a00044  c8127c12              unimplemented (Unimplemented)
    486               0x11a00048  35ffffb2              cbnz w18, #-0xc
    487

After
===
  (comments added manually)

    511     (03) IncProfCounter<1>
    512         Main:
    513               0x2aa00030  d2800100              movz x0, #0x8
    514               0x2aa00034  f2ae0800              movk x0, #0x7040, lsl #16 
    515               0x2aa00038  f2dfffe0              movk x0, #0xffff, lsl #32 
    516               0x2aa0003c  c85f7c12              ldxr x18, [x0]          // <<--- fixed
    517               0x2aa00040  f1000652              subs x18, x18, #0x1 (1) 
    518               0x2aa00044  c8127c12              stxr w18, x18, [x0]     // <<--- fixed
    519               0x2aa00048  35ffffb2              cbnz w18, #-0xc
    520 

Since code generation only generates these two instructions currently, the
others are not yet tested.  The remaining instructions will require an update to
the assembler.

The visitor for the Instrument class will count this as an "other".
The visitor for the Simulator class will report an unimplemented instruction (no change).

### CODE REVIEW

**Comment by fredemmott** [comment]
It'd be good to make the pull request title more descriptive - it's what ends up being the git commit title after import.

**Comment by swalk-cavium** [comment]
You're right of course.  I'll be more careful.

**Comment by fredemmott** [comment]
You should be able to edit it with a button in the top right; if not, comment with what it should be and we'll change it :)

**Comment by mxw** [comment]
Looks like this has some artifacts from another diff—can you rebase onto current master?  Looks good to me otherwise.

**Comment by swalk-cavium** [comment]
Hi Max, 
Which is the artifact?  There was another specifier 's' in the disassembler.  Rather
than introduce extra diffs when/if we bring the latest vixl forward I added the specifier.

If that's not the issue, could you add more words?

**Comment by mxw** [comment]
You're removing some assertions that you removed in a separate PR.

**Comment by swalk-cavium** [comment]
My bad.  I'll fix.

**Comment by swalk-cavium** [comment]
I think I've put the two lines back now.

**Pull request closed without merging**
