### PR TITLE
Add compile time option to disable thrift extension

### PR DESCRIPTION
**Pull request by adsr**
@JoelMarcey This one appears to have the correct path. Not sure what happened in the previous pull request.

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@adsr Hi. Have you gotten this to build correctly? See my comment at 

https://reviews.facebook.net/D31179

**Comment by jrobeson** [comment]
can you possibly add the ability to disable thrift to hhvm-third-party also? that way thrift won't be compiled if not needed.

**Comment by fredemmott** [comment]
Thrift is needed, even if the extension is not available - we use its' concurrency classes in core parts of the runtime.

**Comment by JoelMarcey** [comment]
Closing -- see comments in pull request.

**Pull request closed without merging**
