### PR TITLE
Align thread locals to 16 bytes.

### PR DESCRIPTION
**Pull request by gdbentley**
Commit 8863fc1 changed the order of linking libraries. This caused the layout of thread-local variables to change, revealing a bug in the specification of the necessary alignment for MemoryUsageStats. The compiler was generating a movdqa instruction to access the m_usage field of that object, expecting that field to be 16 byte aligned since it presumed that the beginning of the object would be 16 byte aligned. This change specifies the stricter 16 byte alignment rather than sizeof(void *) (i.e. 8 byte) alignment.

### CODE REVIEW

**Comment by gdbentley** [comment]
This fixes #7112

**Comment by facebook-github-bot-7** [comment]
This pull request has been imported into Phabricator, and discussion and review of the diff will take place at https://reviews.facebook.net/D58983

**Comment by Orvid** [comment]
It's worth noting that there is a known issue (#7104) with trunk on Ubuntu 14.04's version of GCC (I suspect we managed to hit a compiler bug, as it only manifests on 14.04 and release mode), and I'd narrowed it down (manual bisecting) to be caused by one of 10 commits, almost a month before the object libraries change, and I believe @paulbiss kicked off a proper git bisect before leaving yesterday, so we'll see if that fixes the Mediawiki issue before messing with this. It's possible that this is just masking the problem.

**Comment by gdbentley** [comment]
I reproduced this on CentOS 7.

**Comment by apeabody** [comment]
As a note, I have seen some other unexpected segfaults in release builds (but not debug builds) on CentOS 7.  #7115 #7116

CentOS 7:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

**Comment by apeabody** [comment]
I just finished a compile & quick/test, and this commit/pr DOES appear to resolve #7115 and #7116 as well.

**Comment by Orvid** [comment]
The thing is that it shouldn't be happening in the first place :( The best I can guess is that we're hitting either a compiler or linker bug and this may just be masking that.

**Comment by apeabody** [comment]
The issues (#7115 & #7116) I had noted no longer manifests in the current master.  My laptop is too slow to track down the exact commit that resolved them, however I do see changes to MemoryManager which StringData::release() heavily utilizes.

**Comment by gdbentley** [comment]
The root issue was alignment of thread locals. The change to the libraries caused the MemoryManager thread locals to be 8 byte aligned where they had been 16 byte aligned. This caused a movdqa (move double quadword aligned) to have an alignment error manifesting as the segfault.

**Comment by gdbentley** [comment]
088f311 is the commit which inadvertantly fixed #7115 and #7116. It removed the m_stats.usage variable, which was the one getting misaligned.

**Comment by jwatzman** [comment]
@gdbentley was it our JIT incorrectly generating a `movdqa` or a clang/ld bug? I wonder if this is related to 967a98fb807651d585dfe9dfd57e8216fe244c80 where I hit a similar issue, where clang asked for a variable to be 16-byte aligned and generated code assuming that, but OS X ld didn't actually respect that.

**Comment by gdbentley** [comment]
@jwatzman gcc produced the movdqa. I'm not sure that it was incorrect to do so though. I'm not familiar enough with the C++ specification to be sure. If the MemoryUsageStats object were allocated starting at a 16 byte alignment (which it would have been for an ordinary global or a local), then the offset for m_usage would have been 16 byte aligned.

**Comment by Orvid** [comment]
Could you update the summary of the PR in as well?

**Comment by gdbentley** [comment]
@Orvid I presume you meant in phabricator. Done.

**Comment by apeabody** [comment]
@gdbentley - In my experience you will want to change the PR summary in Github (first post).  Unless something has changed recently, if you do it in Phabricator the fb-github-bot will at some point sync over it from github.

**Comment by gdbentley** [comment]
@apeabody Thanks.

**Pull request closed without merging**
