### PR TITLE
Incorrect return value from eval, Closure generated in first eval pass is returned in the second eval pass

### PR DESCRIPTION
**Pull request by ebernhardson**
This is the smallest reproduction case i could put together. Fails on hhvm 3.7.2, 3.6.1 and possibly others.  The 3.7.2 package is the debian package distributed by facebook for ubuntu trusty.

http://3v4l.org/3qEET

    function reproduce( $code ) {
            echo $code, "\n\n";
            $template = eval( $code );
            return $template( array() );
    }

    echo reproduce('return function ($in, $debugopt = 1) {
        return (function() {return "first";})();
    };');
    echo "\n-----\n\n";
    echo reproduce('return function ($in, $debugopt = 1) {
        return (function() {return "second";})();
    };');

Expected Output:
----
    return function ($in, $debugopt = 1) {
        return (function() {return 'first';})();
    };

    first
    -----

    return function ($in, $debugopt = 1) {
        return (function() {return 'second';})();
    };

    second

Actual output
----
    return function ($in, $debugopt = 1) {
        return (function() {return 'first';})();
    };

    first
    -----

    return function ($in, $debugopt = 1) {
        return (function() {return 'second';})();
    };

    first

### CODE REVIEW

**Comment by ebernhardson** [comment]
I pushed a new version of the patch that also puts the above test case into hphp/test/slow/closure/eval_closure.php, but it doesn't seem to have made it into phabricator.

**Comment by jwatzman** [comment]
cc current oncall @JoelMarcey on Phabricator issues, I think he was looking into them earlier today

**Comment by JoelMarcey** [comment]
Yeah, our phabricator syncing is a known problem and I think it is being looked at.

**Comment by JoelMarcey** [comment]
@ebernhardson I imported your diff in this evening. And we got reviewers on it.

**Pull request closed without merging**
