### PR TITLE
General cleanup of ext_pdo

### PR DESCRIPTION
**Pull request by Orvid**
The biggest thing this does is make it so that ext_pdo_sqlite and ext_pdo_mysql aren't used in ext_pdo. This also eliminates the need to declare the individual PDO drivers in pdo_driver.cpp, and instead allows them to be declared in the respective extension, ext_pdo_sqlite / ext_pdo_mysql.

This also eliminates all the global constants in C++ that are not actually needed, and removes the global StaticStrings that were only used once.

This directly depends on #6224 (D46659) and, because this has to include that, will need to be rebased once that is merged.

### CODE REVIEW

**Comment by fredemmott** [comment]
We close pull requests after changes are requested on phabricator for > 1 week. Will re-open when changes are made.

https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Comment by Orvid** [comment]
This was still waiting on #6224 to be merged before I rebased it, as it is directly dependent on it.

**Comment by Orvid** [comment]
@fredemmott Alright, I've rebased this now that the base split is in, if you could re-open this PR, it should show the updated version.

**Comment by jwatzman** [comment]
It says I can't reopen the PR since the branch was force-pushed or recreated. You may have to file another PR, sorry.

**Comment by Orvid** [comment]
Reopened as #6398 (D49137).

**Pull request closed without merging**
