### PR TITLE
Move hhvm-pgsql into core

### LINKED ISSUE #2245: RFC: Add pgsql as bundled DSO
So I've been maintaining `hhvm-pgsql` for a while now as a separate extension, as it could not be easily included in the main tree without introducing a dependency on pgsql. With 7b75fff03900d it looks like that isn't problem any more and the extension could be bundled into the tree.

### PR DESCRIPTION
**Pull request by simonwelsh**
This is a near-direct copy of hhvm-pgsql into the HHVM source tree.

The extension should be optional and will only build if `libpq-dev` is installed on the build server. Running requires a matching `libpq` version (this is `libpq5` on Debian Jessie and Ubuntu 14.04. I don't have servers running other versions of Debian/Ubuntu, so can't check those). 

Once this has been merged, I'll work on moving the Zend ext_pgsql tests, then a HHI file. Will need to figure out how the tests will run internally though, as they require a Postgres server.

I'm submitting this on behalf of PocketRent and the other contributors to hhvm-pgsql. I haven't tried contacting all the individual contributors, so can't reassign the copyright.

Closes #2245 

Test plan: New test that makes sure that both the procedural and PDO versions of ext-pgsql are loaded.

### CODE REVIEW

**Comment by kastermester** [comment]
In case it is needed, in any way, I'm happy with reassigning of copyright for the bits I have contributed.

**Comment by paulbiss** [comment]
@kastermester would you mind signing the CLA https://code.facebook.com/cla ?

**Comment by kastermester** [comment]
@paulbiss Done :)

**Comment by photodude** [comment]
@paulbiss Any plans to move on this?

**Comment by Orvid** [comment]
Yes, there are plans. The changes needed to get it fully covered under the CLA just finished upstream a few days ago.

**Comment by photodude** [comment]
Thanks @Orvid. Looking forward to this being merged and hopefully additional improvements to cover the differences from the Zend pgsql module.

**Pull request closed without merging**
