### PR TITLE
fix segfault when input shorter than all patterns

### PR DESCRIPTION
**Pull request by ebernhardson**
When the input string is shorter than the shortest input
pattern the last position to visit is set to -1. Patch
short circuits and returns input string when all patterns
are longer than the input string.

### CODE REVIEW

**Comment by atdt** [comment]
Reproduction case for the crash that this patch fixes:

```php
<?php
$map = array(
  'ﭐ' => 'ٱ', 'ﭑ' => 'ٱ', 'ﭒ' => 'ٻ', 'ﭓ' => 'ٻ', 'ﭔ' => 'ٻ', 'ﭕ' => 'ٻ', 'ﭖ' => 'پ',
  'ﭗ' => 'پ', 'ﭘ' => 'پ', 'ﭙ' => 'پ', 'ﭚ' => 'ڀ', 'ﭛ' => 'ڀ', 'ﭜ' => 'ڀ', 'ﭝ' => 'ڀ',
  'ﭞ' => 'ٺ', 'ﭟ' => 'ٺ', 'ﭠ' => 'ٺ', 'ﭡ' => 'ٺ', 'ﭢ' => 'ٿ', 'ﭣ' => 'ٿ', 'ﭤ' => 'ٿ',
  'ﭥ' => 'ٿ', 'ﭦ' => 'ٹ', 'ﭧ' => 'ٹ', 'ﭨ' => 'ٹ', 'ﭩ' => 'ٹ', 'ﭪ' => 'ڤ', 'ﭫ' => 'ڤ',
  'ﭬ' => 'ڤ', 'ﭭ' => 'ڤ', 'ﭮ' => 'ڦ', 'ﭯ' => 'ڦ', 'ﭰ' => 'ڦ', 'ﭱ' => 'ڦ', 'ﭲ' => 'ڄ',
  'ﭳ' => 'ڄ', 'ﭴ' => 'ڄ', 'ﭵ' => 'ڄ', 'ﭶ' => 'ڃ', 'ﭷ' => 'ڃ', 'ﭸ' => 'ڃ', 'ﭹ' => 'ڃ',
  'ﭺ' => 'چ', 'ﭻ' => 'چ', 'ﭼ' => 'چ', 'ﭽ' => 'چ', 'ﭾ' => 'ڇ', 'ﭿ' => 'ڇ', 'ﮀ' => 'ڇ',
  'ﮁ' => 'ڇ', 'ﮂ' => 'ڍ', 'ﮃ' => 'ڍ', 'ﮄ' => 'ڌ', 'ﮅ' => 'ڌ', 'ﮆ' => 'ڎ', 'ﮇ' => 'ڎ',
  'ﮈ' => 'ڈ', 'ﮉ' => 'ڈ', 'ﮊ' => 'ژ', 'ﮋ' => 'ژ', 'ﮌ' => 'ڑ', 'ﮍ' => 'ڑ', 'ﮎ' => 'ک',
  'ﮏ' => 'ک', 'ﮐ' => 'ک',
);
strtr( 'ab', $map );
```

**Comment by ebernhardson** [comment]
apologies for not finishing this up yet, still seeing an occasional crash in this code in prod and have not traced it down yet.

**Comment by fredemmott** [comment]
We close pull requests after changes are requested on phabricator for > 1 week. Will re-open when changes are made.

https://github.com/facebook/hhvm/wiki/Human-Timeouts

**Comment by jwatzman** [comment]
Author is coming back to this, per discussion on #6384

**Pull request closed without merging**
