### PR TITLE
Add MySQL PDO Net Read/Write Timeout Config

### PR DESCRIPTION
**Pull request by RyanGordon**
This patch address issue #7627

These settings were previously available in the deprecated MySQL extension, but was never carried over into the PDO MySQL extension. There is a way to set the connect timeout through PDO, but not the read or write timeout. This PR addresses that by adding two new settings that finish wiring through the write_timeout and read_timeout exposed in sql-common/client.c

### CODE REVIEW

**Comment by mofarrell** [comment]
Are these standard?
I can't find any documentation for them in PHP
http://php.net/manual/en/pdo.constants.php

**Comment by RyanGordon** [comment]
No, these aren't standard (They're not in upstream PHP PDO). These are completely new parameters that allow us to set MYSQL_OPT_READ_TIMEOUT and PDO_ATTR_WRITE_TIMEOUT as implemented in the MySQL client library: https://github.com/mysql/mysql-server/blob/71f48ab393bce80a59e5a2e498cd1f46f6b43f9a/sql-common/client.c#L5699 (docs here: https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html)

**Comment by mofarrell** [comment]
@wez I believe you implemented most of pdo.  What do you think about this?  Since we don't have mysqli we are leaning towards accepting this.

**Comment by Orvid** [comment]
If they aren't standard they should be placed in the `HH\` namespace.

**Comment by wez** [comment]
If no other database drivers have a concept of a separated read vs. write timeout (it's been a while since I looked, and they didn't way back then), this would be motivation for making these PDO_MYSQL specific.  The pre-namespaces way of dealing with a driver specific attribute in PDO is to use `PDO_MYSQL_` as the prefix for the global constant that is being defined.

It should be a similar trivial patch to the upstream PHP to make whatever naming we settle on here work with both implementations.

**Comment by RyanGordon** [comment]
That sounds good, should I move this to both `HH\` namespace and rename to be `PDO_MYSQL_` or just rename to `PDO_MYSQL_`?

**Comment by Orvid** [comment]
Sorry it's taken so long to reply, I missed your response :( `HH_PDO_MYSQL` is reasonable. As these are class constants, moving them into the `HH` namespace is a bit more difficult that it would otherwise be.

**Comment by RyanGordon** [comment]
Sounds good! I will change them to HH_PDO_MYSQL and test it out and push it asap

**Pull request closed without merging**
