### PR TITLE
Trivial tweaks

### PR DESCRIPTION
**Pull request by nazar-pc**
This is preparation for landing support for compressed Phar files.
As discussed in #4263 changes that doesn't affect code logic separated for easier review.
This PR primarily includes manual edits of PhpDoc sections to conform with arguments names from PHP documentation and to make them understandable to IDE. Also some Exceptions classes changed as it is defined in PHP docs.

### CODE REVIEW

**Comment by Orvid** [comment]
This seems to have dropped all of the summaries from the doc comments, could we not do that?

**Comment by nazar-pc** [comment]
Initially I saw most functions without them, so for consistency I've also removed some. My goal was to get sane IDE support, comments are available in PHP docs anyway, but it is handy to have arguments types in source code.

Should I bring them back?

**Comment by Orvid** [comment]
If the summaries were already there, as is the case here, keep them.

**Comment by nazar-pc** [comment]
Restored what was already present

**Pull request closed without merging**
