### PR TITLE
Build system for Hack on Windows

### PR DESCRIPTION
**Pull request by OCamlPro-Henry**
This PR contains a build-system for Hack on windows. It relies on OCPWin (as described in `hphp/hack/README.win32`). This alternative build system may also be used on Linux and OS X (see `hphp/hack/README.ocp-build`).

*Warnings*: on Windows, the resulting binaries are not working yet, all tests are known to fail.

The main file describing the build process is `hphp/hack/src/build.ocp`. It defines a set of libraries and programs. The library architecture has been sketched with our young knownledge about Hack. If someone with more experience could have a look at it, it would be appreciated.

Some additional descriptions specific to Hack (i.e. not required when build Flow) may be found in the following files:

- `hphp/hack/build.ocp`
- `hphp/hack/src/h2tp/build.ocp`

While in the long term it might require some efforts to maintain two build systems, for now we take care not to modify (and not to conflict with) the current build system.

### CODE REVIEW

**Comment by fredemmott** [comment]
Just to share the state: FB are waiting for corporate CLA before merge/review.

**Comment by OCamlPro-Henry** [comment]
Just to be clear, the corporate CLA has been signed yesterday.

**Comment by fredemmott** [comment]
cc @jamesgpearce

**Comment by fredemmott** [comment]
@OCamlPro-Henry : was this via the web interface, email, or snail mail?

**Comment by OCamlPro-Henry** [comment]
CC @MuSSF

**Comment by OCamlPro-Henry** [comment]
@fredemmott @MuSSF signed via the web interface. And she signed once more today.

**Pull request closed without merging**
