### PR TITLE
Aarch64 - Use architecture zero reg when lowering store*i

### PR DESCRIPTION
**Pull request by swalk-cavium**
There were numerous places where a zero immediate was being
written to memory.  Aarch64 has a dedicated zero valued register.
This is one place where it can be used to reduce the dynamic instruction
count.  The example below was taken from the regression test 
hhvm/hphp/test/zend/good/ext/intl/tests/grapheme.php
  
 Before
=====
    326  B3: [profCount=1] (preds B0) 
    327     (08) SpillFrame<-3,0> t1:StkPtr, t3:Func, Nullptr
    328         Main:
    329               0x1e2008e8  f81e03a0              stur x0, [x29, #-32]
    330               0x1e2008ec  52800000              movz w0, #0x0   <<-------------
    331               0x1e2008f0  b81ec3a0              stur w0, [x29, #-20]

After
=====
     17480  B3: [profCount=1] (preds B0) 
     17481     (08) SpillFrame<-3,0> t1:StkPtr, t3:Func, Nullptr
     17482         Main:
     17483               0x1b400864  f81e03a0              stur x0, [x29, #-32]
     17484               0x1b400868  b81ec3bf              stur wzr, [x29, #-20]

This was tested by running the regression suite with 6 different option sets.
No new issues were found.

### CODE REVIEW

**Comment by mxw** [comment]
What is the "regression suite" and what are the "6 different option sets"?

**Comment by mxw** [comment]
(This change lgtm though.)

**Comment by swalk-cavium** [comment]
echo "Test Started - `date`"

HPHP_TEST=all
PATH=`pwd`/hphp/hhvm:${PATH}
 
echo "/usr/bin/php hphp/test/run -v -m interp ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m interp ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m interp -r ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m interp -r ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=0' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=0' ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=0' ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=1' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -a '-vEval.JitPGO=1' ${HPHP_TEST} || true

echo "/usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1' ${HPHP_TEST}"
      /usr/bin/php hphp/test/run -v -m jit -r -a '-vEval.JitPGO=1' ${HPHP_TEST} || true

echo "Test Ended - `date`"

**Comment by mxw** [comment]
@swalk-cavium—Can you rebase this diff over recent master?  A diff from @dave-estes that I upstreamed has a conflict with it.

**Comment by swalk-cavium** [comment]
@mxw - Updated yesterday.  Forgot to send prompt.  Should be ready to go.

**Pull request closed without merging**
