### PR TITLE
AArch64 speedup warmup times by reading cpufreq files

### PR DESCRIPTION
**Pull request by jim-saxman**

### CODE REVIEW

**Comment by jim-saxman** [comment]
Hi @mxw, @swalk-cavium. Would you please review this PR.

**Comment by swalk-cavium** [comment]
@jim-saxman - I'm not seeing MHz entries in /proc/cpuinfo on our machines.  @apinski-cavium recalled that changing the contents was Nak'd on the ARM kernel mailing list.
http://lists.infradead.org/pipermail/linux-arm-kernel/2017-September/533228.html

Which distro are you testing with?

**Comment by jim-saxman** [comment]
Hi @swalk-cavium This patch checks  /sys/device/system/cpu/cpu*/cpufreq/cpuinfo_max_freq if available, on ARM, just like /proc/cpuinfo is read on x64. If you don't have cpufreq, then this patch will work as before (no change in performance).

**Comment by jim-saxman** [comment]
This pull request no longer provides any performance benefit, so I'm closing it.

**Pull request closed without merging**
