### PR TITLE
Replace translator-asm-helpers.S' magic registers to synonyms as defined by abi

### PR DESCRIPTION
**Pull request by gut**
Summary: Improved code readability by replacing the following:
%rbx -> ETCH_R_VM_SP
%r12 -> ETCH_R_VM_TL
%rbp -> ETCH_R_VM_FP

This also reduces efforts to make new ports based on existing code.

### CODE REVIEW

**Comment by fredemmott** [comment]
Ping - waiting for CLA.

**Comment by gut** [comment]
right, just a sec

**Comment by fredemmott** [comment]
Did you submit the CLA? If so, how?

**Comment by gut** [comment]
Not yet. I'm waiting for an internal approval... I'll ping here when it's done. Sorry for that

**Comment by gut** [comment]
Same goal, but now also took care of handleSRHelper function that is also inside of translator-asm-helpers.S

**Comment by gut** [comment]
@fredemmott : Are these new commits also going to be exported to the same Phabricator review?

**Comment by jwatzman** [comment]
(Still waiting on a CLA, please do ping when it's ready :))

**Comment by gut** [comment]
Yes, sorry. Dealing with attorney...

**Comment by jwatzman** [comment]
No problem, we're happy to wait as long as it takes, just occasionally pinging this to make sure that nothing got accidentally stuck in limbo (e.g., you sent in the CLA but it didn't get entered into the system).

**Comment by gut** [comment]
Hello @jwatzman, the corporate CLA was signed an hour ago.

**Comment by jwatzman** [comment]
Which corporation? I'll forward this on to the guy who knows how to properly enter corp CLAs into our system (we basically need to have you marked as being a member of the corporation on our end).

**Comment by gut** [comment]
Instituto de Pesquisas Eldorado,
Further information, like my corporate email, you can find on my github profile.
Thanks

**Comment by gut** [comment]
The Review was accepted in Phabricator on 18th December:
https://reviews.facebook.net/D48117

however the change is not yet merged nor this pull request has been closed yet. Normally it doesn't take that long so I wonder if something went wrong?

**Comment by JoelMarcey** [comment]
@gut Hmmm... we meant to land this manually, but it failed for some reason. Let me look into it.

**Pull request closed without merging**
