### PR TITLE
[PPC64] Improve decoder and other low level asm/disasm

### PR DESCRIPTION
**Pull request by gut**

### CODE REVIEW

**Comment by gut** [comment]
@mxw : Hi. Can you check if those failed tests are indeed a concern?

**Comment by aorenste** [comment]
@gut - @mxw approved this internally and it's in the process of being pushed so I would guess the tests are fine.
:)

**Comment by gut** [comment]
@aorenste ok, thanks.

**Comment by Orvid** [comment]
The failed test was just something being flaky. It's not an issue with this diff.

**Pull request closed without merging**
