### PR TITLE
Update Joomla to 3.4.1

### PR DESCRIPTION
**Pull request by photodude**

### CODE REVIEW

**Comment by photodude** [comment]
@fredemmott does a new PR for this need to be opened or can this one be reopened?

**Comment by fredemmott** [comment]
Please send a new PR; try also deleteing framework_downloads before re-running. If this works correctly, we would expect to see a change to one of the .expect files too, not just frameworks.yaml.

**Comment by photodude** [comment]
@fredemmott I'll have to see about setting up a local environment and updating in the same fashion as  adding a new framework for a new PR. This PR was created by just modifying frameworks.yaml via github.com

**Comment by fredemmott** [comment]
Ah, OK, that explains why it doesn't work. Yep, this'll need testing before sending. The yaml file also tries to disable tests that don't exist in this version.

**Comment by photodude** [comment]
Good to know, I'll have to review the tests list for additions and removals too.

**Comment by fredemmott** [comment]
Please actually run it.
- Most additions and removals will be fine
- Removals are only a problem if they are referenced in the yaml file for some reason - and the script will tell you about these. Manual review shouldn't be neccessary
- You need to run it to generate the expect file anyway.

**Comment by photodude** [comment]
Will, do. 

Are there guidlines on what tests are necessary to be included in the yaml file, or is all of that handled by the run?

**Comment by fredemmott** [comment]
They're only added if they're problematic for some reason - eg if take an hour to run, or are unreliable (assuming that calling time() twice in a row gives the same result is a common one).

**Comment by photodude** [comment]
So in general practice, would it be best to remove all of the tests for the framework from the yaml file and then add them back if they are "problematic for some reason"?

**Comment by fredemmott** [comment]
Leave them as-is. Remove them if there's a reason to - eg they don't exist any more, or the test has been modified.

It can take many runs to find out which tests fail intermittently, so giving it a clean slate each time it's updated isn't generally a good idea.

**Comment by fredemmott** [comment]
oh, you'll want to run with --record to update the .expect file, instead of merely compare against it.

**Pull request closed without merging**
